### ISSUE TITLE
False targeted link in README.md

### ISSUE THREAD

**Issue by rnuredini** [tuanavu/coursera-university-of-washington#2]
The link to quiz-week4-assignment.ipynb in:
 [https://github.com/tuanavu/coursera-university-of-washington/blob/master/machine_learning/1_machine_learning_foundations/README.md](url) 
points to 
[https://github.com/tuanavu/coursera-university-of-washington/blob/master/machine_learning/1_machine_learning_foundations/lecture/week4/quiz-week4-lecture.ipynb](url). 
Instead it should point to: 
[https://github.com/tuanavu/coursera-university-of-washington/blob/master/machine_learning/1_machine_learning_foundations/assignment/week4/quiz-week4-assignment.ipynb](url)

**Comment by tuanavu** [comment]
Hi @rnuredini,

Thanks for the info. The link is updated.
